//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceTimingDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_category
    {
        public long id { get; set; }
        public Nullable<long> categories_id { get; set; }
        public Nullable<long> competitions_id { get; set; }
        public Nullable<long> player_id { get; set; }
        public Nullable<long> competitions_competition_id { get; set; }
    
        public virtual category category { get; set; }
        public virtual competition competition { get; set; }
        public virtual competition competition1 { get; set; }
        public virtual player player { get; set; }
    }
}
