//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceTimingDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RaceTimingEntities : DbContext
    {
        public RaceTimingEntities()
            : base("name=RaceTimingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<competition> competitions { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<player> players { get; set; }
        public virtual DbSet<player_category> player_category { get; set; }
        public virtual DbSet<role> roles { get; set; }
    }
}
